!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/C4_Context.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/C4_Component.puml

skinparam DefaultFontSize 10
skinparam componentStyle rectangle

SHOW_PERSON_OUTLINE()

!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/sms.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/credit_card.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/input.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/import_export.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/envelope.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/money_bill_wave.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/react.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/scriptcs.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/java.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/server.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/database.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/notifications.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/angular.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/angularjs.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/credit_card.puml
!include https://raw.githubusercontent.com/BraveH/C4_Generic/refs/heads/main/icons/shopping_cart.puml
!global $LEGEND_TITLE_COLOR = "#Gray"

AddElementTag("new_component", $bgColor="#Purple", $fontColor="#FFFFFF", $shadowing="true")
AddElementTag("no_change", $bgColor="#Gray", $fontColor="#FFFFFF", $shadowing="true")
AddElementTag("impacted_component", $bgColor="#Darkorange",$fontColor="#FFFFFF", $shadowing="true")

skinparam sequenceMessageAlign center
skinparam style stricture
hide footbox
hide unlinked
skinparam sequence {
    LifeLineBackgroundColor #A9DCDF
    LifeLineBorderColor #368E92
    group {
    FontStyle plain
    BackGroundColor wight
  }
  groupHeader {
    FontStyle plain
    FontColor red
  }

}

LAYOUT_TOP_DOWN()
